import {readProviderError} from './provider-errors';
import {navigateAndObserve,readPageObservation,type CdpCall} from './browser-cdp';
import {openBrowserSocket} from './browser-socket';
import {connection,db,now,record,seal,uid,unseal} from './server';
type BrowserRow={id:string;owner:string;project:string;provider_id:string;secret:string;state:string;expires:number};
class BrowserServiceError extends Error{status:number;constructor(status:number,message:string){super(message);this.status=status;}}
export function publicUrl(value:unknown){if(typeof value!=='string'||value.length>2048)throw new Error('Enter a public HTTPS URL.');const u=new URL(value);const host=u.hostname.toLowerCase();if(u.protocol!=='https:'||u.username||u.password||u.port&&u.port!=='443'||!host.includes('.')||/^\d+(\.\d+){3}$/.test(host)||host.includes(':')||['localhost','local','internal','test','invalid'].some(t=>host===t||host.endsWith('.'+t)))throw new Error('Only public HTTPS hostnames are allowed.');return u.toString();}
function serviceUrl(value:string,protocol='https:'){const u=new URL(value);if(u.protocol!==protocol||!u.hostname.endsWith('.browserbase.com')||u.username||u.password)throw new Error('The browser service returned an unexpected URL.');return u.toString();}
async function browserApi(owner:string,path:string,data?:unknown){const c=await connection(owner,'browserbase');if(!c)throw new Error('Connect Browserbase in Settings to open a remote browser.');const r=await fetch('https://api.browserbase.com/v1/sessions'+path,{method:data?'POST':'GET',redirect:'error',headers:{'X-BB-API-Key':c.key,'Content-Type':'application/json'},body:data?JSON.stringify(data):undefined,signal:AbortSignal.timeout(25000)});if(!r.ok){const issue=await readProviderError(r,c.key,'browserbase');throw new BrowserServiceError(r.status,'Browserbase ('+r.status+(issue.code?'/'+issue.code:'')+'): '+(issue.detail||issue.hint));}return r.json() as Promise<any>;}
async function browserRow(owner:string,project:string,id:string){const row=await db().prepare('SELECT * FROM browser_sessions WHERE id=? AND owner=? AND project=?').bind(id,owner,project).first<BrowserRow>();if(!row)throw new Error('Browser session not found.');return row;}
export async function browserFor(owner:string,project:string,id?:string){const row=id?await browserRow(owner,project,id):await db().prepare("SELECT * FROM browser_sessions WHERE owner=? AND project=? AND state='active' AND expires>? ORDER BY created DESC LIMIT 1").bind(owner,project,Date.now()).first<BrowserRow>();if(!row)throw new Error('No active browser for this workspace.');if(row.expires<Date.now()||row.state!=='active')throw new Error('Browser session expired. Start a new session.');return row;}
export async function startBrowser(owner:string,project:string){
 await db().prepare("UPDATE browser_sessions SET state='expired' WHERE owner=? AND project=? AND state='active' AND expires<=?").bind(owner,project,Date.now()).run();
 const existing=await db().prepare("SELECT id FROM browser_sessions WHERE owner=? AND project=? AND state='active' AND expires>?").bind(owner,project,Date.now()).first();if(existing)throw new Error('A browser is already active. Open it or end it first.');
 const session=await browserApi(owner,'',{timeout:600,keepAlive:true,browserSettings:{viewport:{width:1280,height:800},solveCaptchas:false,recordSession:false,logSession:false,ignoreCertificateErrors:false}});
 if(typeof session.id!=='string'||!session.connectUrl)throw new Error('Browser service returned an invalid session.');
 try{const debug=await browserApi(owner,'/'+encodeURIComponent(session.id)+'/debug');const live=serviceUrl(debug.debuggerFullscreenUrl);const connect=serviceUrl(session.connectUrl,'wss:');const id=uid(),expires=Date.now()+600000;
 await db().prepare('INSERT INTO browser_sessions(id,owner,project,provider_id,secret,state,created,expires) VALUES(?,?,?,?,?,?,?,?)').bind(id,owner,project,session.id,await seal(owner,JSON.stringify({live,connect})),'active',now(),expires).run();await record(owner,project,'browser.started',{id,expires});return {id,liveUrl:live,expires};
 }catch(e){await browserApi(owner,'/'+encodeURIComponent(session.id),{status:'REQUEST_RELEASE'}).catch(()=>{});throw e;}
}
export async function getBrowserView(owner:string,project:string,id?:string){const row=await browserFor(owner,project,id);const credentials=JSON.parse(await unseal(owner,row.secret));return {id:row.id,expires:row.expires,liveUrl:serviceUrl(credentials.live)};}
export async function stopBrowser(owner:string,project:string,id:string){const row=await browserRow(owner,project,id);if(row.state==='closed')return;try{await browserApi(owner,'/'+encodeURIComponent(row.provider_id),{status:'REQUEST_RELEASE'});}catch(e){if(!(e instanceof BrowserServiceError)||![404,409].includes(e.status))throw e;}await db().prepare("UPDATE browser_sessions SET state='closed',secret='' WHERE id=? AND owner=?").bind(id,owner).run();await record(owner,project,'browser.stopped',{id});}
// Minimal CDP transport for the remote service only. No client-supplied CDP endpoint or arbitrary method is accepted.
async function cdp(owner:string,row:BrowserRow,task:(call:CdpCall,sessionId:string)=>Promise<any>){
 const credentials=JSON.parse(await unseal(owner,row.secret));const endpoint=serviceUrl(credentials.connect,'wss:');
 const socket=await openBrowserSocket(endpoint);let next=0;const pending=new Map<number,{resolve:(value:any)=>void;reject:(error:Error)=>void;timer:ReturnType<typeof setTimeout>}>();
 const rejectAll=()=>{for(const entry of pending.values()){clearTimeout(entry.timer);entry.reject(new Error('Browser control disconnected.'));}pending.clear();};
 socket.addEventListener('message',(event:{data:unknown})=>{let message:any;try{const raw=typeof event.data==='string'?event.data:event.data instanceof ArrayBuffer?new TextDecoder().decode(new Uint8Array(event.data)):'';if(!raw)return;message=JSON.parse(raw);}catch{return;}const entry=pending.get(message.id);if(!entry)return;clearTimeout(entry.timer);pending.delete(message.id);if(message.error)entry.reject(new Error('The browser rejected this action.'));else entry.resolve(message.result);});socket.addEventListener('close',rejectAll);socket.addEventListener('error',rejectAll);
 const call:CdpCall=(method,params={},sessionId)=>new Promise<any>((resolve,reject)=>{const id=++next;const timer=setTimeout(()=>{pending.delete(id);reject(new Error('Browser action timed out.'));},15000);pending.set(id,{resolve,reject,timer});try{socket.send(JSON.stringify({id,method,params,...(sessionId?{sessionId}:{})}));}catch{clearTimeout(timer);pending.delete(id);reject(new Error('Browser action could not be sent.'));}});
 try{const targets=await call('Target.getTargets');let target=targets.targetInfos?.find((t:any)=>t.type==='page'&&!t.url?.startsWith('devtools:'));if(!target){const created=await call('Target.createTarget',{url:'about:blank'});target={targetId:created.targetId};}const attached=await call('Target.attachToTarget',{targetId:target.targetId,flatten:true});return await task(call,attached.sessionId);}finally{rejectAll();try{socket.close(1000,'Action complete');}catch{}}
}
export async function navigateBrowser(owner:string,project:string,url:string,id?:string){const target=publicUrl(url),row=await browserFor(owner,project,id);const result=await cdp(owner,row,(call,sid)=>navigateAndObserve(call,sid,target));await record(owner,project,'browser.navigated',{id:row.id,origin:new URL(target).origin,settled:result.settled});return result;}
export async function readBrowser(owner:string,project:string,id?:string){const row=await browserFor(owner,project,id);return cdp(owner,row,(call,sid)=>readPageObservation(call,sid));}
