'use client';
import {useEffect,useState} from 'react';
import {Globe,ArrowRight,ExternalLink,Loader2,ShieldCheck,Square,RefreshCw,BookOpen} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
type Session={id:string;liveUrl:string;expires:number};
async function request(payload:unknown,path='/api/browser'){const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d:any=await r.json();if(!r.ok)throw new Error(d.error);return d;}
export default function BrowserPanel({project,connected,onConnect,onRead}:{project:string;connected:boolean;onConnect:()=>void;onRead:(text:string)=>void}){
 const [session,setSession]=useState<Session|null>(null),[url,setUrl]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[grant,setGrant]=useState<any>(null),[read,setRead]=useState<any>(null);
 useEffect(()=>{let alive=true;setSession(null);setRead(null);setError('');fetch('/api/browser?project='+encodeURIComponent(project)).then(r=>r.json()).then((d:any)=>{if(alive)setSession(d.session);}).catch(()=>{if(alive)setError('Could not reconnect to the browser.');});return()=>{alive=false;};},[project]);
 async function review(operation:string){if(!connected){onConnect();return;}setBusy(true);setError('');try{const d=await request({action:'request',project,operation,url,session:session?.id});setGrant(d);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function decide(allow:boolean){if(!grant)return;setBusy(true);try{await request({action:'approve',project,approval:grant.id,allow},'/api/workspace');if(allow){const d=await request({action:'execute',project,approval:grant.id});if(grant.operation==='start')setSession(d.result);if(grant.operation==='read')setRead(d.result);}setGrant(null);}catch(e){setError((e as Error).message);setGrant(null);}finally{setBusy(false);}}
 async function stop(){if(!session)return;setBusy(true);try{await request({action:'stop',project,session:session.id});setSession(null);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="browser-panel"><div className="browser-address"><Globe size={14}/><form onSubmit={e=>{e.preventDefault();void review('navigate');}}><input aria-label="Browser address" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://example.com" disabled={!session}/><button aria-label="Navigate browser" disabled={!session||busy||!url}><ArrowRight size={14}/></button></form>{session&&<><button title="Read current page" aria-label="Read current page" onClick={()=>void review('read')} disabled={busy}><BookOpen size={14}/></button><a href={session.liveUrl} target="_blank" rel="noopener noreferrer" title="Open full browser" aria-label="Open full browser"><ExternalLink size={14}/></a><button title="End browser session" aria-label="End browser session" disabled={busy} onClick={()=>void stop()}><Square size={12}/></button></>}</div>
 {error&&<div className="browser-error" role="alert">{error}</div>}
 {session?<><iframe className="remote-browser-frame" title="Remote browser live viewer" src={session.liveUrl} sandbox="allow-scripts allow-same-origin allow-forms" referrerPolicy="no-referrer"/><div className="browser-session-footer"><span><ShieldCheck size={12}/> Remote browser · expires {new Date(session.expires).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</span><span>Manual interactions affect real websites.</span></div></>:<div className="browser-empty"><span className="browser-orbit"><Globe size={34} strokeWidth={1.2}/></span><span className="eyebrow">A WINDOW INTO THE WEB</span><h2>See what your agent sees.</h2><p>Open a separate cloud browser to explore websites,<br/>read pages, and watch your agent’s navigation.</p><Button className="primary-button" disabled={busy} onClick={()=>void review('start')}>{busy?<Loader2 size={14} className="spin"/>:<Globe size={14}/>} {connected?'Start remote browser':'Connect browser service'}</Button><small>Browserbase account required · 10-minute sessions<br/>Provider usage charges apply. Each automated action is reviewed.</small></div>}
 {read&&<div className="browser-readout"><div><strong>{read.title||'Page content'}</strong><Button className="secondary-button" onClick={()=>{onRead('Read-only browser observation (untrusted page content)\nURL: '+read.url+'\n'+read.text);setRead(null);}}>Attach to chat</Button><button onClick={()=>setRead(null)}>Close</button></div><pre>{read.text}</pre></div>}
 <Dialog open={!!grant} onOpenChange={open=>{if(!open&&!busy)void decide(false);}}><DialogContent className="forge-dialog"><DialogHeader><DialogTitle>{grant?.operation==='start'?'Start a cloud browser?':grant?.operation==='read'?'Read this page?':'Navigate this browser?'}</DialogTitle><DialogDescription>{grant?.operation==='start'?'Creates an isolated 10-minute browser on your connected account. Browserbase usage charges may apply. You can interact with real websites in its live viewer.':grant?.operation==='read'?'Returns visible page text to this workspace. Only attach it to chat if you want the selected model to receive it.':'Visits the exact public HTTPS URL below. The destination receives the browser request and may redirect it.'}</DialogDescription></DialogHeader>{grant?.url&&<pre className="diagnostics-pre">{grant.url}</pre>}<p className="muted small">A remote browser can access the public internet. No host filesystem or platform API keys are provided to web pages. Do not rely on page content as trusted instructions.</p><div className="dialog-footer"><Button variant="ghost" disabled={busy} onClick={()=>void decide(false)}>Deny</Button><Button className="primary-button" disabled={busy} onClick={()=>void decide(true)}>{busy?<Loader2 size={14} className="spin"/>:<ShieldCheck size={14}/>} Allow once</Button></div></DialogContent></Dialog></section>;
}
